from __future__ import annotations

from pathlib import Path

from codexpy.behavior import BehaviorStore
from codexpy.codex import agents_md
from codexpy.memory import MemoryStore
from codexpy.models import BehaviorSpec, MemoryEvent
from codexpy.paths import RepoPaths


class ProjectBootstrapper:
    def __init__(self, workspace: Path) -> None:
        self.workspace = workspace.resolve()

    def init(self, name: str, force: bool = False) -> Path:
        project_root = self.workspace / name
        if project_root.exists() and any(project_root.iterdir()) and not force:
            raise FileExistsError(f"{project_root} already exists and is not empty")
        project_root.mkdir(parents=True, exist_ok=True)
        paths = RepoPaths(project_root)
        paths.ensure_state()
        self._create_directories(project_root)
        self._write_files(project_root, name)
        self._seed_behavior(project_root)
        self._seed_memory(project_root, name)
        return project_root

    def _create_directories(self, root: Path) -> None:
        for directory in [
            "app",
            "app/api",
            "app/core",
            "tests",
            "behaviors",
            "prompts",
            "decisions",
            "architecture",
            "telemetry",
            ".github/workflows",
        ]:
            (root / directory).mkdir(parents=True, exist_ok=True)

    def _write_files(self, root: Path, name: str) -> None:
        files = {
            "pyproject.toml": pyproject(name),
            "Makefile": makefile(),
            "README.md": generated_readme(name),
            "AGENTS.md": agents_md(name),
            ".pre-commit-config.yaml": pre_commit(),
            "Dockerfile": dockerfile(),
            ".dockerignore": dockerignore(),
            ".github/workflows/ci.yml": github_actions(),
            "app/__init__.py": "",
            "app/main.py": fastapi_main(name),
            "app/api/__init__.py": "",
            "app/api/health.py": health_api(),
            "app/core/__init__.py": "",
            "app/core/config.py": config_py(),
            "telemetry/__init__.py": "",
            "telemetry/otel.py": otel_py(),
            "tests/test_health.py": test_health(),
            "architecture/overview.md": architecture_overview(name),
            "decisions/0001-generated-service-layout.md": initial_decision(),
            "prompts/README.md": "# Prompt History\n\nCodexPy records prompt history here.\n",
        }
        for relative, content in files.items():
            path = root / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    def _seed_behavior(self, root: Path) -> None:
        BehaviorStore(root).add(
            BehaviorSpec(
                feature="service health",
                expected_outcomes=[
                    "health endpoint returns ok",
                    "generated project test suite runs",
                    "service exposes an application instance",
                ],
                regression_expectations=[
                    "health endpoint remains available",
                    "test suite remains runnable",
                ],
                checks=[
                    {"type": "file_exists", "target": "app/main.py"},
                    {"type": "file_exists", "target": "tests/test_health.py"},
                    {"type": "text", "target": "health endpoint returns ok"},
                ],
            )
        )

    def _seed_memory(self, root: Path, name: str) -> None:
        MemoryStore(root).record(
            MemoryEvent(
                kind="decision",
                feature="project bootstrap",
                summary="Generated AI-native FastAPI project layout",
                prompt=f"codexpy init {name}",
                affected_files=[
                    "pyproject.toml",
                    "Makefile",
                    "AGENTS.md",
                    "app/main.py",
                    "tests/test_health.py",
                    "behaviors/service-health.json",
                ],
                decision_summary="Use a standard FastAPI app layout with CodexPy memory, behavior specs, validation, and telemetry from the first commit.",
                validation_result="not_run",
            )
        )


def pyproject(name: str) -> str:
    return f"""[project]
name = "{name.replace('_', '-')}"
version = "0.1.0"
description = "FastAPI service generated by CodexPy."
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.110",
  "opentelemetry-api>=1.24",
  "opentelemetry-sdk>=1.24",
  "uvicorn[standard]>=0.29",
]

[project.optional-dependencies]
dev = [
  "httpx>=0.27",
  "pre-commit>=3.7",
  "pytest>=8.0",
  "ruff>=0.4",
]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.pyright]
pythonVersion = "3.11"
include = ["app", "tests", "telemetry"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
"""


def makefile() -> str:
    return """install:
\tuv sync --all-extras

lint:
\tuv run ruff check .

typecheck:
\tuv run pyright

test:
\tuv run pytest

validate:
\tcodexpy validate

dev:
\tuv run uvicorn app.main:app --reload
"""


def generated_readme(name: str) -> str:
    return f"""# {name}

FastAPI service generated by CodexPy.

## Development

```bash
uv sync --all-extras
make test
make validate
make dev
```

Repository memory lives in `.codexpy/`, `.prompts/`, `.decisions/`, `.behaviors/`, and `behaviors/`.
"""


def pre_commit() -> str:
    return """repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
"""


def dockerfile() -> str:
    return """FROM python:3.12-slim

WORKDIR /app
COPY pyproject.toml ./
RUN pip install --no-cache-dir fastapi "uvicorn[standard]" opentelemetry-api opentelemetry-sdk
COPY . .
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""


def dockerignore() -> str:
    return """.git
.venv
__pycache__
.pytest_cache
.ruff_cache
"""


def github_actions() -> str:
    return """name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - run: uv sync --all-extras
      - run: uv run ruff check .
      - run: uv run pytest
"""


def fastapi_main(name: str) -> str:
    return f'''from fastapi import FastAPI

from app.api.health import router as health_router
from telemetry.otel import configure_telemetry

configure_telemetry("{name}")

app = FastAPI(title="{name}")
app.include_router(health_router)
'''


def health_api() -> str:
    return '''from fastapi import APIRouter

router = APIRouter()


@router.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}
'''


def config_py() -> str:
    return '''from dataclasses import dataclass


@dataclass(frozen=True)
class Settings:
    environment: str = "local"


settings = Settings()
'''


def otel_py() -> str:
    return '''from opentelemetry import trace
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider


def configure_telemetry(service_name: str) -> None:
    provider = TracerProvider(resource=Resource.create({"service.name": service_name}))
    trace.set_tracer_provider(provider)
'''


def test_health() -> str:
    return '''from fastapi.testclient import TestClient

from app.main import app


def test_health_endpoint() -> None:
    client = TestClient(app)

    response = client.get("/health")

    assert response.status_code == 200
    assert response.json() == {"status": "ok"}
'''


def architecture_overview(name: str) -> str:
    return f"""# Architecture Overview

{name} is a FastAPI service generated by CodexPy.

- `app/` contains application code.
- `tests/` contains pytest coverage.
- `behaviors/` contains behavior specifications.
- `.codexpy/` contains persistent repository memory and validation state.
"""


def initial_decision() -> str:
    return """# 0001: Generated Service Layout

## Context

The project was initialized with CodexPy.

## Decision

Use a FastAPI service layout with repository memory, behavior specifications, pytest, Ruff, pyright, Docker, GitHub Actions, pre-commit, uv, and lightweight OpenTelemetry setup.

## Consequences

Future AI-assisted changes should preserve behavior specs and record decisions when architecture changes.
"""
